<?php

namespace Container1Fa3jVc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBorrowingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iHNdZ5r.App\Entity\Borrowing' shared service.
     *
     * @return \App\Entity\Borrowing
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iHNdZ5r": it needs an instance of "App\\Entity\\Borrowing" but this type has been excluded in "config/services.yaml".');
    }
}
