<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4Ug6wl\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4Ug6wl/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerA4Ug6wl.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerA4Ug6wl\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerA4Ug6wl\App_KernelProdContainer([
    'container.build_hash' => 'A4Ug6wl',
    'container.build_id' => 'd0f6b9c3',
    'container.build_time' => 1732656025,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4Ug6wl');
