<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \App\Entity\Book implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annee_edition' => [parent::class, 'annee_edition', null],
        "\0".parent::class."\0".'borrowings' => [parent::class, 'borrowings', null],
        "\0".parent::class."\0".'editeur' => [parent::class, 'editeur', null],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isbn' => [parent::class, 'isbn', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'annee_edition' => [parent::class, 'annee_edition', null],
        'borrowings' => [parent::class, 'borrowings', null],
        'editeur' => [parent::class, 'editeur', null],
        'etat' => [parent::class, 'etat', null],
        'id' => [parent::class, 'id', null],
        'isbn' => [parent::class, 'isbn', null],
        'titre' => [parent::class, 'titre', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
