<?php

namespace ContainerA4Ug6wl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBorrowingTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\BorrowingType' shared autowired service.
     *
     * @return \App\Form\BorrowingType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BorrowingType'] = new \App\Form\BorrowingType();
    }
}
