<?php

namespace ContainerA4Ug6wl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBorrowingControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BorrowingController' shared autowired service.
     *
     * @return \App\Controller\BorrowingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BorrowingController'] = $instance = new \App\Controller\BorrowingController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\BorrowingController', $container));

        return $instance;
    }
}
