<?php

namespace ContainerA4Ug6wl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HistoryRepository' shared autowired service.
     *
     * @return \App\Repository\HistoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HistoryRepository'] = new \App\Repository\HistoryRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
