<?php

namespace ContainerA4Ug6wl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoryControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\HistoryController' shared autowired service.
     *
     * @return \App\Controller\HistoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\HistoryController'] = $instance = new \App\Controller\HistoryController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\HistoryController', $container));

        return $instance;
    }
}
