<?php

namespace ContainerA4Ug6wl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignUpTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SignUpType' shared autowired service.
     *
     * @return \App\Form\SignUpType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SignUpType'] = new \App\Form\SignUpType();
    }
}
