<?php

namespace ContainerHEnCCpH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoryControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mSaexrr.App\Controller\HistoryController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mSaexrr.App\\Controller\\HistoryController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'borrowingRepository' => ['privates', 'App\\Repository\\BorrowingRepository', 'getBorrowingRepositoryService', true],
        ], [
            'borrowingRepository' => 'App\\Repository\\BorrowingRepository',
        ]))->withContext('App\\Controller\\HistoryController::index()', $container);
    }
}
