<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHEnCCpH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHEnCCpH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHEnCCpH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHEnCCpH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHEnCCpH\App_KernelDevDebugContainer([
    'container.build_hash' => 'HEnCCpH',
    'container.build_id' => '8128640e',
    'container.build_time' => 1733987380,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHEnCCpH');
