<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBTJQSQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBTJQSQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBTJQSQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBTJQSQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHBTJQSQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'HBTJQSQ',
    'container.build_id' => '4a84f4ec',
    'container.build_time' => 1732957115,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBTJQSQ');
